/**
* @File Name : Constants.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : September 16, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | September 16, 2024 |   | Initial Version
**/

public class Constants {
	public static final String knowledgeCommunityName = 'SaurabhKnowledgePortal';
}